/* Minimal H5build_settings stub for static build via Zig.
 *
 * The real file is generated by CMake from H5build_settings.cmake.c.in.
 * We provide a minimal version since the library still references
 * the H5build_settings[] symbol.
 */

#include "H5private.h"

const char H5build_settings[] =
    "       SUMMARY OF THE HDF5 CONFIGURATION\n"
    "       =================================\n"
    "\n"
    "HDF5 Version: 2.1.1\n"
    "Built with Zig build system (SIEtoHDF5 project)\n"
    "Static library, no MPI, no threading, no compression filters\n"
;
